language: go

go:
  - 1.8.3
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get github.com/Masterminds/glide
  - glide install
  - go install
  - orbit run lint-install

script:
  - orbit run lint test

notifications:
  email: false