sudo: required

language: generic

services:
  - docker

before_install:
  - wget -qO- https://github.com/gulien/orbit/releases/download/v3.0.0/orbit_Linux_x86_64.tar.gz | tar xvz -C .
  - sudo mv ./orbit /usr/local/bin && chmod +x /usr/local/bin/orbit

script:
  - orbit run ci -p "Version,${TRAVIS_BRANCH}"
  # Uploads coverage.
  - bash <(curl -s https://codecov.io/bash)