[[companies]]
name = "SpaceX"
launchers = ["Falcon 9", "Falcon Heavy"]

[[companies]]
name = "Blue Origin"
launchers = ["New Shepard", "New Glenn"]

[[agencies]]
name = "ESA"
launchers = ["Ariane 5", "Vega"]